FROM python:3.9-bullseye
RUN apt-get update -y
RUN apt-get install build-essential -y
RUN apt-get install doxygen -y

RUN apt-get install swig -y

RUN pip install --upgrade pip

RUN pip install swig
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# expose port for gradio app
EXPOSE 7860
